DELETE FROM DB_STG2PARTND2.HLH WHERE TRUE;

INSERT INTO ${STGPARTN_DB}.HLH 
SELECT
    MC.HLH_SK,
    MC.RW_EFF_DT,
    MC.CLM_ID AS CLM_ID,
    CAST('9999-12-31' AS DATE FORMAT 'YYYY-MM-DD') AS RW_EXP_DT,
    1111 AS ETL_BATCH_SK,
    CURRENT_DATETIME() AS AEDW_LAST_UPDT_TS
FROM
    DB_SRCD2.MASTER MC
    INNER JOIN ${SRC_DB}.CLM HC ON HC.CLM_ID=MC.CLM_ID;
 