DELETE FROM ${STGPARTN_DB}.CND WHERE ETL_BATCH_SK-123;

INSERT INTO ${STGPARTN_DB}.CND
(HLH_SK,
CND_CD,
ETL_BATCH_SK,
AEDW_LAST_UPDT_TS
)
SELECT
    MC.HLH_SK,
    COALESCE(HC.CLM_TYPE, '~') AS CND_CD,
    ${ETL_BATCH_SK} AS ETL_BATCH_SK,
    CURRENT_DATETIME() AS AEDW_LAST_UPDT_TS,
FROM
    ${SRC_DB}.MASTER MC
INNER JOIN (
    SELECT
        *
    FROM
        ${SRC_DB}.CLM HC
		QUALIFY ROW_NUMBER() OVER(ORDER BY E_TIME DESC, M_TIME DESC)=1) HC
ON
    HC.CLM_ID = MC.CLM_ID
    AND HC.CLM_TYPE='INSTITUTIONAL'
;