DELETE FROM ${STGPARTN_DB}.CLAIM WHERE ETL_BATCH_SK=${ETL_BATCH_SK};
 

INSERT INTO ${STGPARTN_DB}.CLAIM (HLH_SK, LN_ID, RW_EFF_DT, RW_EXP_DT, ETL_BATCH_SK, AEDW_LAST_UPDT_TS) 
 
SELECT
    MC.HLH_SK,
    1 AS LN_ID,
    MC.RW_EFF_DT,
    CAST('9999-12-31' AS DATE FORMAT 'YYYY-MM-DD') AS RW_EXP_DT,
    ${ETL_BATCH_SK} AS etl_batch_sk,
    CURRENT_DATETIME() AS AEDW_LAST_UPDT_TS
FROM
    ${SRC_DB}.MASTER MC
    INNER JOIN ${SRC_DB}.CLM HC ON HC.CLM_ID=MC.CLM_ID;