DELETE FROM ${AEDW_DB}.ETL_JOB_DTL WHERE ETL_INTF_CD='MM10835';

INSERT INTO DB_AEDWD2.ETL_JOB_DTL 
VALUES ('MM10835,'TEMP@GMAIL.COM','DUMMY@GMAIL.COM');
INSERT INTO ${AEDW_DB}.ETL_JOB_DTL 
VALUES ('MM10835','11234@GMAIL.COM','ALSLS@GMAIL.COM');

