INSERT INTO ${AEDW_DB}.REJ_RSN_CD 
SELECT REJ_RSN_CD,
'DESCRIPTION TO BE DETERMINED' AS REJ_RSN_DSC,
PAYEE_1_CD,
'~' AS REJ_RSN_PLN_ID,
1 AS ETL_BATCH_SK,
CURRENT_TIMESTAMP AS AEDW_LAST_UPDT_TS 
FROM ${SRC_DB}.REJ_RSN_CD_TEMP SRC 
WHERE SRC.ETL_BATCH_SK=${ETL_BATCH_SK}; 